"""add columns to conversation_messages

Revision ID: ae158f6c281d
Revises: c6f8b3404847
Create Date: 2026-07-09 17:49:34.236585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae158f6c281d'
down_revision: Union[str, Sequence[str], None] = 'c6f8b3404847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_messages', sa.Column('model', sa.String(length=100), nullable=False))
    op.add_column('conversation_messages', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('conversation_messages', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_messages', 'completion_tokens')
    op.drop_column('conversation_messages', 'prompt_tokens')
    op.drop_column('conversation_messages', 'model')
    # ### end Alembic commands ###
