"""add is_active

Revision ID: d8b2b167ada1
Revises: 1e664b426e2d
Create Date: 2026-07-15 17:15:35.949540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8b2b167ada1'
down_revision: Union[str, Sequence[str], None] = '1e664b426e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'prompt_templates', 
        sa.Column(
            'is_active', 
            sa.Boolean(), 
            nullable=False, 
            server_default=sa.true()
        )
    )
    # ### end Alembic commands ###
    op.alter_column(
        "prompt_templates",
        "is_active",
        server_default=None
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_templates', 'is_active')
    # ### end Alembic commands ###
